const availableJobs = [
  {
    title: "Software Engineer",
    description: "This is specific to backend development with nodejs",
    employer: "ASG",
    location: "Kampala-Uganda",
    created_date: Date.now().toString(),
    numOfPos: 4,
    duration: "4 days",
    status: "active",
  },
  {
    title: "Accountant",
    description: "We're looking for a proffessional ACP accountant.",
    employer: "AR Tech",
    location: "Nairobi Kenya",
    created_date: Date.now().toString(),
    numOfPos: 1,
    duration: "2 weeks",
    status: "active",
  },
  {
    title: "Sales",
    description: "Door to door sells person.",
    employer: "AWG",
    location: "Kampala-Uganda",
    created_date: Date.now().toString(),
    numOfPos: 5,
    duration: "6 hours",
    status: "active",
  },
  {
    title: "Driver",
    description: "Light weight vehicle driver for our CEO",
    employer: "MTN",
    location: "Kampala-Uganda",
    created_date: Date.now().toString(),
    numOfPos: 5,
    duration: "1 month",
    status: "active",
  },
  {
    title: "Data Engineer",
    description:
      "Preferably a data scientist who is familiar with data collection",
    employer: "AAR",
    location: "Dar Tanzania",
    created_date: Date.now().toString(),
    numOfPos: 2,
    duration: "1 week",
    status: "active",
  },
  {
    title: "Electrical Engineer",
    description: "Specific to indoor installation and cabling.",
    employer: "Apple",
    location: "Kampala-Uganda",
    created_date: Date.now().toString(),
    numOfPos: 4,
    duration: "4 days",
    status: "active",
  },
];

module.exports = availableJobs;
